name: Push

on: push
jobs:
  verify:
    uses: ./.github/workflows/verify.yml
  artifactory:
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
          check-latest: true
      - name: Deploy to Artifactory
        run: mvn deploy -Partifactory
